In [ ]:
#!/usr/bin/python

""" 
    Starter code for exploring the Enron dataset (emails + finances);
    loads up the dataset (pickled dict of dicts).

    The dataset has the form:
    enron_data["LASTNAME FIRSTNAME MIDDLEINITIAL"] = { features_dict }

    {features_dict} is a dictionary of features associated with that person.
    You should explore features_dict as part of the mini-project,
    but here's an example to get you started:

    enron_data["SKILLING JEFFREY K"]["bonus"] = 5600000
    
"""

import pickle

enron_data = pickle.load(open("../final_project/final_project_dataset.pkl", "r"))

In [44]:
len(enron_data)

146

In [ ]:
x = 0 
for key,value in enron_data.iteritems():
    print value['poi']==True
    if(value['poi']==True):
        x=x+1
x

In [ ]:
for key,value in enron_data.iteritems():
    print key

In [ ]:
enron_data

In [78]:
import pandas as pd
df = pd.DataFrame(enron_data)
df = df.transpose()
# df = df.dropna()
# df['email_address'].isnull().any()
import numpy as np
total_payment = np.array(df[['total_payments']])
total_payment.
# df.sort(['total_payments'], ascending=[0]).dropna()

array([[4484442],
       [182466],
       [916197],
       [5634343],
       [827696],
       [860136],
       [969068],
       [5501630],
       [102500],
       [228474],
       [618850],
       [15456290],
       [2047593],
       [2014835],
       [1279],
       [2669589],
       [49288],
       [1054637],
       [1271582],
       [2355702],
       [1639297],
       [477557],
       [1868758],
       ['NaN'],
       ['NaN'],
       ['NaN'],
       [1490344],
       ['NaN'],
       [1101393],
       [807956],
       [1208649],
       [4747979],
       [550981],
       [1204583],
       [1410464],
       [2368151],
       [319941],
       [875760],
       [77492],
       [2093263],
       [2692324],
       [211725],
       [3676340],
       [2424083],
       [1414857],
       ['NaN'],
       [181755],
       [17252530],
       [50591],
       [900585],
       [1566469],
       ['NaN'],
       [966522],
       ['NaN'],
       [1272284],
       [2146973],
       [119292],
       [1146658],
       [3859065],
       [288682],
       [475],
       [7961],
       ['NaN'],
       [1297461],
       [2081796],
       [91093],
       [3131860],
       ['NaN'],
       [3100224],
       [1979596],
       [551174],
       [83750],
       [1086821],
       [1747522],
       [704896],
       [3471141],
       [1587421],
       [2652612],
       [10425757],
       [103559793],
       [2664228],
       [87492],
       ['NaN'],
       [875889],
       ['NaN'],
       ['NaN'],
       [8407016],
       ['NaN'],
       [1318763],
       [2101364],
       ['NaN'],
       [4099771],
       [148],
       [1061827],
       [2151],
       [1848227],
       ['NaN'],
       [628522],
       [3202070],
       [812194],
       [774401],
       [1321557],
       [249787],
       [3123383],
       [27942],
       [1386690],
       [1737629],
       ['NaN'],
       ['NaN'],
       [564348],
       [111529],
       [394475],
       [505050],
       [1099100],
       [3750],
       ['NaN'],
       [3038702],
       [1057548],
       [1576511],
       [2003885],
       ['NaN'],
       [4335388],
       [8682716],
       [1112087],
       [999356],
       [1545059],
       [1092663],
       [362096],
       [911453],
       [399393],
       [309886585],
       [1130461],
       [228656],
       [213071],
       [1798780],
       [87410],
       [1034395],
       [762135],
       ['NaN'],
       [4677574],
       [1934359],
       [84992],
       [189583],
       ['NaN'],
       [360300],
       [55097]], dtype=object)

In [57]:
enron_data['LAY KENNETH L']

{'bonus': 7000000,
 'deferral_payments': 202911,
 'deferred_income': -300000,
 'director_fees': 'NaN',
 'email_address': 'kenneth.lay@enron.com',
 'exercised_stock_options': 34348384,
 'expenses': 99832,
 'from_messages': 36,
 'from_poi_to_this_person': 123,
 'from_this_person_to_poi': 16,
 'loan_advances': 81525000,
 'long_term_incentive': 3600000,
 'other': 10359729,
 'poi': True,
 'restricted_stock': 14761694,
 'restricted_stock_deferred': 'NaN',
 'salary': 1072321,
 'shared_receipt_with_poi': 2411,
 'to_messages': 4273,
 'total_payments': 103559793,
 'total_stock_value': 49110078}

In [58]:
df['email_address'].size

146

In [55]:
import

,ALLEN PHILLIP K,BADUM JAMES P,BANNANTINE JAMES M,BAXTER JOHN C,BAY FRANKLIN R,BAZELIDES PHILIP J,BECK SALLY W,BELDEN TIMOTHY N,BELFER ROBERT,BERBERIAN DAVID,...,WASAFF GEORGE,WESTFAHL RICHARD K,WHALEY DAVID A,WHALLEY LAWRENCE G,WHITE JR THOMAS E,WINOKUR JR. HERBERT S,WODRASKA JOHN,WROBEL BRUCE,YEAGER F SCOTT,YEAP SOON
bonus,4175000,NaN,NaN,1200000,400000,NaN,700000,5249999,NaN,NaN,...,325000,NaN,NaN,3000000,450000,NaN,NaN,NaN,NaN,NaN
deferral_payments,2869717,178980,NaN,1295738,260455,684694,NaN,2144013,-102500,NaN,...,831299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
deferred_income,-3081055,NaN,-5104,-1386055,-201641,NaN,NaN,-2334434,NaN,NaN,...,-583325,-10800,NaN,NaN,NaN,-25000,NaN,NaN,NaN,NaN
director_fees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3285,NaN,...,NaN,NaN,NaN,NaN,NaN,108579,NaN,NaN,NaN,NaN
email_address,phillip.allen@enron.com,NaN,james.bannantine@enron.com,NaN,frank.bay@enron.com,NaN,sally.beck@enron.com,tim.belden@enron.com,NaN,david.berberian@enron.com,...,george.wasaff@enron.com,dick.westfahl@enron.com,NaN,greg.whalley@enron.com,thomas.white@enron.com,NaN,john.wodraska@enron.com,NaN,scott.yeager@enron.com,NaN
exercised_stock_options,1729541,257817,4046157,6680544,NaN,1599641,NaN,953136,3285,1624396,...,1668260,NaN,98718,3282960,1297049,NaN,NaN,139130,8308552,192758
expenses,13868,3486,56301,11200,129142,NaN,37172,17355,NaN,11892,...,NaN,51870,NaN,57838,81353,1413,NaN,NaN,53947,55097
from_messages,2195,NaN,29,NaN,NaN,NaN,4343,484,NaN,NaN,...,30,NaN,NaN,556,NaN,NaN,NaN,NaN,NaN,NaN
from_poi_to_this_person,47,NaN,39,NaN,NaN,NaN,144,228,NaN,NaN,...,22,NaN,NaN,186,NaN,NaN,NaN,NaN,NaN,NaN
from_this_person_to_poi,65,NaN,0,NaN,NaN,NaN,386,108,NaN,NaN,...,7,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,NaN
loan_advances,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
long_term_incentive,304805,NaN,NaN,1586055,NaN,93750,NaN,NaN,NaN,NaN,...,200000,256191,NaN,808346,NaN,NaN,NaN,NaN,NaN,NaN
other,152,NaN,864523,2660303,69,874,566,210698,NaN,NaN,...,1425,401130,NaN,301026,1085463,NaN,189583,NaN,147950,NaN
poi,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
restricted_stock,126027,NaN,1757552,3942714,145796,NaN,126027,157569,NaN,869220,...,388167,384930,NaN,2796177,13847074,NaN,NaN,NaN,3576206,NaN
restricted_stock_deferred,-126027,NaN,-560222,NaN,-82782,NaN,NaN,NaN,44093,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary,201955,NaN,477,267102,239671,80818,231330,213999,NaN,216582,...,259996,63744,NaN,510364,317543,NaN,NaN,NaN,158403,NaN
shared_receipt_with_poi,1407,NaN,465,NaN,NaN,NaN,2639,5521,NaN,NaN,...,337,NaN,NaN,3920,NaN,NaN,NaN,NaN,NaN,NaN
to_messages,2902,NaN,566,NaN,NaN,NaN,7315,7991,NaN,NaN,...,400,NaN,NaN,6019,NaN,NaN,NaN,NaN,NaN,NaN
total_payments,4484442,182466,916197,5634343,827696,860136,969068,5501630,102500,228474,...,1034395,762135,NaN,4677574,1934359,84992,189583,NaN,360300,55097
total_stock_value,1729541,257817,5243487,10623258,63014,1599641,126027,1110705,-44093,2493616,...,2056427,384930,98718,6079137,15144123,NaN,NaN,139130,11884758,192758

In [72]:
import numpy as np
np.array(df)

array([[4175000, 2869717, -3081055, ..., 2902, 4484442, 1729541],
       ['NaN', 178980, 'NaN', ..., 'NaN', 182466, 257817],
       ['NaN', 'NaN', -5104, ..., 566, 916197, 5243487],
       ...,
       ['NaN', 'NaN', 'NaN', ..., 'NaN', 'NaN', 139130],
       ['NaN', 'NaN', 'NaN', ..., 'NaN', 360300, 11884758],
       ['NaN', 'NaN', 'NaN', ..., 'NaN', 55097, 192758]], dtype=object)